auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("create_list/",views.create_list, name="create_list"),
    path("listing_page/<int:id>/",views.listing_page, name="listing_page"),
    path("add_to_watchlist/<int:id>/",views.add_to_watchlist,name="add_to_watchlist"),
    path("remove_from_watchlist/<int:id>/",views.remove_from_watchlist,name="remove_from_watchlist"),
    path("watchlist/",views.watchlist_view,name="watchlist"),
    path("add_bid/",views.add_bid, name="add_bid"),
    path("bid_history/<int:id>/",views.bid_history, name="bid_history"),
    path("close_auction/<int:id>/",views.close_auction,name="close_auction"),
    path("add_comment/<int:id>/",views.add_comment, name="add_comment"),
    path('categories/<str:category>/',views.categories_view,name="categories"),
    path('my_listing/',views.my_listing_view, name='my_listing')
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static

from auctions.sitemap import *

sitemaps = {
    'static' : StaticViewSitemap,
    'categorie':CategorieViewSitemap,
    'listing_page' : Listing_pageViewSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("sitemap.xml",sitemap,{'sitemaps':sitemaps}),
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE, PROTECT
from datetime import datetime
from django.shortcuts import reverse

class User(AbstractUser):
    pass

class categories(models.Model):
    categorie = models.CharField(max_length=22, unique=True)

    def __str__(self):
        return self.categorie  

    def get_absolute_url(self):
        return reverse("categories", kwargs={"category": self.categorie})
      

class Auction(models.Model):
    author = models.ForeignKey(User, on_delete= CASCADE, default=1)
    title = models.CharField(max_length=23)
    categorie = models.ForeignKey(categories ,on_delete=models.CASCADE, default=5)
    image = models.CharField(max_length=2048,blank=True)
    bid = models.IntegerField()
    description = models.TextField()
    isActive = models.BooleanField(default=True,blank=True)
    watchlist = models.ManyToManyField(User,blank=True,related_name="watchlist")


    def __str__(self):
        return f"{self.title} "

    def get_absolute_url(self):
        return reverse("listing_page", kwargs={"id": self.pk})

class Bids(models.Model):
    stuff = models.ForeignKey(Auction, on_delete = CASCADE)
    bidder = models.ForeignKey(User,on_delete = models.DO_NOTHING)
    time = models.DateTimeField(datetime.now())
    val = models.IntegerField()

class Comments(models.Model):
    stuff = models.ForeignKey(Auction, on_delete = CASCADE)
    author = models.ForeignKey(User, on_delete = models.DO_NOTHING)
    time = models.DateTimeField(default = datetime.now())
    text = models.TextField()

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django import forms
from datetime import datetime
import auctions

from .models import User, Auction,Bids,Comments,categories

class Auctions(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ['author','title','categorie','image','bid','description']
        widgets = {
            'author': forms.HiddenInput(attrs={'value':'1'}),
            'title' : forms.TextInput( attrs={'class':'form-input'}),
            'categorie' : forms.Select( attrs={'class' : 'form-input'}),
            'image' : forms.TextInput( attrs={'placeholder':'Insert Url','class' : 'form-input'}),
            'bid' : forms.NumberInput(attrs={'class':'form-input','min':1,'max': 999999999}),
            'description' : forms.Textarea( attrs={'class':'form-input'}),
        }

def index(request):
    image = None
    if request.method == "POST":
         form = Auctions(request.POST)
         form.save()
         temp = Auction.objects.all().last()
         temp.author = User.objects.get(pk = request.user.pk)
         temp.save()
    
    #check it the current item is in the watchlist of the current user
    stuff_in_watchlist = []
    for stuff in Auction.objects.filter(isActive = True):
        stuff_in_watchlist.append(stuff.watchlist.filter(pk = request.user.pk).exists())

    #merge stuff_in_watchlist and Auction.objects.first(isActive = True)
    stuffs = zip(Auction.objects.filter(isActive = True),stuff_in_watchlist)

    return render(request, "auctions/index.html",{
        'title' : "Active Listings",
        'auction': stuffs,
        'path':'index',
    })

def login_view(request):
    if request.method == "GET" and request.GET.get('next'):
        return render(request, "auctions/login.html",{
            'next' : request.GET.get('next')
        })

    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            if request.POST['next'] != None and request.POST['next'] != '':
                return redirect(request.POST['next'])
            
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def create_list(request):
    return render(request,"auctions/create_list.html",{
        "form":Auctions,
    })

def listing_page(request,id):
    stuff = Auction.objects.get(pk=id)
    message = None

    if stuff.isActive == False:
        bidder = Bids.objects.filter(stuff= stuff)
        if (Bids.objects.filter(stuff= stuff).count() > 0):
            if bidder.last().bidder == request.user:
                message = 'Congratulations, you won the auction'

    return render(request,'auctions/listing_page.html',{
        'auction':Auction.objects.get(pk=id),
        'message':message,
        'comments':Comments.objects.filter(stuff = id),
        'in_watchlist':Auction.objects.get(pk=id).watchlist.filter(pk = request.user.pk).exists(),
        'path':f'listing_page/{id}',
    })

def add_to_watchlist(request,id):
    stuff = Auction.objects.get(pk = id)
    stuff.watchlist.add(request.user)
    if (request.GET['next'] == 'index'):
        return HttpResponseRedirect("/")
    return  HttpResponseRedirect(f"/{request.GET['next']}/")

def remove_from_watchlist(request,id):
    Auction.objects.get(pk = id).watchlist.remove(request.user)
    if (request.GET['next'] == 'index'):
        return HttpResponseRedirect("/")
    return  HttpResponseRedirect(f"/{request.GET['next']}/")

def watchlist_view(request):
    auction = []
    stuff_in_watchlist = []
    for stuff in Auction.objects.all():
        if (stuff.watchlist.filter(pk = request.user.pk).exists()):
            auction.append(stuff)
            stuff_in_watchlist.append(True)

    stuffs =  zip(auction,stuff_in_watchlist)

    return render(request, "auctions/index.html",{
        'title' : "Watchlist",
        'auction': stuffs,
        'path':'watchlist'
    })

def add_bid(request):
    current_stuff = Auction.objects.get(pk = request.POST['pk'])
    if (int(request.POST['amount']) <= current_stuff.bid):
        return render(request,'auctions/listing_page.html',{
            'auction':Auction.objects.get(pk=request.POST['pk']),
            'error' : "You have to bid more than £" + str(current_stuff.bid) + ".00"
        })

    newbid = Bids(stuff = current_stuff,bidder=request.user,time=datetime.now(),val = request.POST['amount'])
    newbid.save()

    current_stuff.bid = request.POST['amount']
    current_stuff.save()

    return render(request,'auctions/listing_page.html',{
        'auction':Auction.objects.get(pk=request.POST['pk']),
        'success' : "Your bid was successful"
    })

def bid_history(request,id):
    stuff = Auction.objects.get(pk = id)
    bids = Bids.objects.filter(stuff = stuff)
    return render(request,"auctions/bid_history.html",{
        'bid':bids
    })

def close_auction(request,id):
    stuff = Auction.objects.get(pk=id)
    stuff.isActive = False
    stuff.save()
    return  HttpResponseRedirect(f"/listing_page/{id}/")

def add_comment(request,id):
    if request.method == "POST":
        Stuff = Auction.objects.get(pk = request.POST['stuff'])
        comments = Comments(stuff = Stuff,author = request.user, text = request.POST['comment-input'],time=datetime.now())
        comments.save()
    return  listing_page(request,id)

def  categories_view(request,category):
    if category == 'All':
        stuffs =  Auction.objects.all()
    else:
        temp = categories.objects.get(categorie = category)
        stuffs = Auction.objects.filter(categorie = temp, isActive = True)

     #check it the current item is in the watchlist of the current user
    stuff_in_watchlist = []
    for stuff in stuffs:
        stuff_in_watchlist.append(stuff.watchlist.filter(pk = request.user.pk).exists())

    #merge stuff_in_watchlist and Auction.objects.first(isActive = True)
    stuffs = zip(stuffs,stuff_in_watchlist)

    return render(request,'auctions/categories.html',{
        'title' : f"{category} Listings",
        'auction': stuffs,
        'path':f'categories/{category}',
    })

def my_listing_view(request):
    #check it the current item is in the watchlist of the current user
    stuff_in_watchlist = []
    for stuff in Auction.objects.filter(author = request.user):
        stuff_in_watchlist.append(stuff.watchlist.filter(pk = request.user.pk).exists())

    #merge stuff_in_watchlist and Auction.objects.filter(author = request.user)
    stuffs = zip(Auction.objects.filter(author = request.user),stuff_in_watchlist)

    return render(request, "auctions/index.html",{
            'title' : "My Listings",
            'auction': stuffs,
            'path':'index',
    })

auctions/templates/auctions/bid_history.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <h1>Bid History</h1>
    <table>
        <tr>
            <th>
                Bidder
            </th>
            <th>
                Bid Amount
            </th>
            <th>
                Bid Time
            </th>
        </tr>
            {% for x in bid reversed %}
                <tr>
                    <td>
                        {{x.bidder}}
                    </td>
                    <td>
                        {{x.val}}
                    </td>
                    <td>
                        {{x.time}}
                    </td>
                </tr>
            {% endfor %}
    </table>

{% endblock body %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>{{title}}</h1>
    <div id="auctions-container">
        {% for n,stuff_in_watchlist in auction %}
            <div id="card">
                <h2>{{ n.title }}
                    {% if not n.isActive %}
                    <button class="btn disabled">Closed</button>
                    {% endif %}
                </h2>
                <div style="height: 200px;">
                    <img id="img" src="{{n.image}}" onerror="standby()"/>
                </div>
                    <p>Current bid: £{{ n.bid }}.00</p>
                    <h5 style="margin-bottom:0px;">Description</h5>
                    <textarea style="resize:none;margin-bottom:10px;width:95%" cols="39" rows="4" readonly>{{ n.description }}</textarea>
                    {% if user.is_authenticated %}
                        {% if stuff_in_watchlist %}
                            <a id="remove-watchlist" href="{% url 'remove_from_watchlist' n.pk %}?next={{path}}&number=0">Remove Watchlist</a>
                        {% else %}
                            <a href="{% url 'add_to_watchlist' n.pk %}?next={{path}}&number=0">Add Watchlist</a>
                        {% endif %}
                        <a href="{% url 'listing_page' n.pk %}">View</a>
                    {% else %}
                        <a href="{% url 'listing_page' n.pk %}" style="padding-top:10px;padding-bottom:10px">View</a>
                    {% endif %}
            </div>
        {% endfor %}
        <div style="clear:left">
        </div>
    </div>

{% endblock %}

auctions/templates/auctions/create_list.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <form action="{% url 'index' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <input type="hidden" name="author" value ="{{user.pk}}">
        {{ form.as_p }}
        <input type="submit" value="Save" class="btn">
    </form>
{% endblock body %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>{{title}}</h1>
    <div id="auctions-container">
        {% for n,stuff_in_watchlist in auction %}
            <div id="card">
                <h2>{{ n.title }}
                    {% if not n.isActive %}
                    <button class="btn disabled">Closed</button>
                    {% endif %}
                </h2>
                <div style="height: 200px;">
                    <img id="img" src="{{n.image}}" onerror="standby(this)"/>
                </div>
                <div style="position:absolute;bottom:0px;">
                    <p>Current bid: £{{ n.bid }}.00</p>
                    <h5 style="margin-bottom:0px;">Description</h5>
                    <textarea style="resize:none;margin-bottom:10px;width:95%" cols="39" rows="4" readonly>{{ n.description }}</textarea>
                    {% if user.is_authenticated %}
                        {% if stuff_in_watchlist %}
                            <a id="remove-watchlist" href="{% url 'remove_from_watchlist' n.pk %}?next={{path}}">Remove Watchlist</a>
                        {% else %}
                            <a href="{% url 'add_to_watchlist' n.pk %}?next={{path}}">Add Watchlist</a>
                        {% endif %}
                        <a href="{% url 'listing_page' n.pk %}">View</a>
                    {% else %}
                    <a href="{% url 'listing_page' n.pk %}" style="padding-top:10px;padding-bottom:10px">View</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div style="clear:left">
        </div>
    </div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Auctions{% endblock %}</title>
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="body">
            <nav class="nav-bar">
                <span class="left" >
                    <a id="logo-img" href="{% url 'index' %}"><img style="vertical-align:middle;" src="https://cdn-icons-png.flaticon.com/512/345/345629.png" alt="icon" width="50px"/></a>
                    <a id="logo-txt" href="{% url 'index' %}"><b>Auctions</b></a>
                    <label id="nav-link" name="categories" style="padding-bottom:20px">Categories</label>
                    {% if user.is_authenticated %}
                        <a href="{% url 'create_list' %}" id="nav-link">Create listing</a>
                    {% else %}
                        <a id="nav-link" href="{% url 'login' %}">Log In</a>
                        <a id="nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                    <div id="sub-menu">
                        <a href="{% url 'categories' 'All' %}">All</a> <br>
                        {% for category in categories %}
                            <a href="{% url 'categories' category %}">{{category}}</a> <br>
                        {% endfor %}
                    </div>
                </span>


                <span class="right">
                    {% if user.is_authenticated %}
                        <strong name="user-name">{{ user.username }}</strong>
                        <div id="sub-menu">
                            <a href="{% url 'watchlist' %}">Watchlist</a> <br>
                            <a href="{% url 'my_listing' %}">My listing</a><br>
                            <hr>
                            <a href="{% url 'logout' %}">Log out</a>
                        </div>
                       
                    {% else %}
                        Not signed in.
                    {% endif %}
                </span>
            </nav>
            <br/>
            {% block body %}
            {% endblock %}

        </div>

        <footer style="clear:both">
            
        </footer>
        <script src="{% static 'auctions/index.js' %}"></script>
    </body>


</html>

auctions/templates/auctions/listing_page.html
{% extends 'auctions/layout.html' %}


{% block body %}
    {% if error %}
        <p class="msg" id="error">{{error}}</p>
    {% endif %}
    {% if success %}
        <p class="msg" id="success">{{success}}</p>
    {% endif %}
    {% if message %}
    <p class="msg" id="success">{{message}}</p>
    {% endif %}
    <h1>{{ auction.title }} 
        {% if auction.isActive == False %}
            <button class="btn disabled" disabled>Closed</button>
            {% else %}
                {% if user.is_authenticated %}
                    {% if auction.author == user %}
                        <a href="{% url 'close_auction' auction.pk %}"><button style="padding: .375rem .75rem;">Close</button></a>
                    {% endif %}
                {% endif %} 
        {% endif %}
        {% if user.is_authenticated %}
            {% if in_watchlist %}
                <a class="watchlist-link" id="remove-watchlist" style="padding-left:2.2rem;padding-right:2.2rem;width:auto;" href="{% url 'remove_from_watchlist' auction.pk %}?next={{path}}">Remove Watchlist</a>
            {% else %}
                <a class="watchlist-link" style="padding-left:2.2rem;padding-right:2.2rem;width:auto;" href="{% url 'add_to_watchlist' auction.pk %}?next={{path}}">Add Watchlist</a>
            {% endif %}
        {% else %}
            <span style="font-size:16px;font-weight:normal"><a href="{% url 'login' %}?next={{request.path}}">Login</a> to add it in the watchlist</span>
        {% endif %}
 
    </h1>
        <div style="border: 1px solid rgba(0,0,0,.125);background-color: white;padding:25px 25px;margin-right: 10px;">
            <div id="img-container">
                <img id="img" src="{{auction.image}}" onerror="standby()"/>
            </div>
    
            <div>
                <p>Categorie: {{auction.categorie}}</p>
                <h5 style="margin-bottom:0px;">Description</h5>
                <p style="word-wrap:break-word">{{ auction.description }}</p>  
                <div style="background-color:#e2e2e2;padding-left: 5px;">
                    <p>Bid history: <a href="{% url 'bid_history' id=auction.pk %}">{{ auction.bids_set.count }}</a></p>
                    <p>Current price: £{{ auction.bid }}.00</p>
                    {% if auction.isActive %}
                        {% if user.is_authenticated %}
                            <form action="{% url 'add_bid' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="pk" value="{{auction.pk}}">
                                <input type="hidden" name="path" value="{{request.path}}">
                                <label for="amount">£</label>
                                <input type="number" name="amount" style="font-size:1rem;width:min(160px,70%);" placeholder="Bid Amount" required>
                                <label for="amount">.00</label>
                                <p style="color:#767676;margin:0;font-size:12px;">Enter more than £{{ auction.bid }}.00</p>
                                <input type="submit" style="width:min(150px,90%);margin:2px;" value="Place bid" class="btn">
                            </form>
                        {% else %}
                            <a href="{% url 'login' %}?next={{request.path}}">Login</a> to bid
                            <button disabled>Place bid</button>
                        {% endif %}
                    {% else %}
                        <button class="btn disabled" style="margin-bottom:10px" disabled>Auction is closed</button>
                    {% endif %}

                    
                </div>   
            </div>

            <div style="clear: left;"></div>
        </div>

        <div>
            <h2>Comments</h2>
            {% if user.is_authenticated %}
                <form action="{% url 'add_comment' auction.pk %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="stuff" value="{{auction.pk}}">
                    <input id="comment-input" name="comment-input" type="text" placeholder="Add a public comment..." onkeyup="check_input()">
                    <hr>
                    <hr id="black-hr">
                    <button style="float: right;margin-left: 10px;" class="btn disabled" id="Add-comment"><b>Add comment</b></button>
                    <label style="float: right;" class="btn" onclick="clear_input()"><b>Cancel</b></label>
                    <div style="clear:right"></div>
                </form>
            {% else %}
                <a href="{% url 'login' %}?next={{request.path}}">Login</a> to comment
            {% endif %}
            {% if comments %}
                <div id="comments-container">
                    {% for comment in comments reversed %}
                        <div style="margin-bottom:0px;">
                            <img style="width:40px" src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0=">
                            <span style="position:relative;top:-10px;">
                                <b>{{comment.author}}</b>
                                (time: 
                                <b>{{comment.time | date:'Y/m/d, H:i' }}</b>)
                            </span>
                        </div>
                        <p>{{comment.text}}</p>
                        <hr>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
{% endblock body %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}